name: Docker Image CI

on:
  push:
    branches: [ "main", "refactor-to-backend-frontend" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refactor-to-backend-frontend
      - name: Set image name
        id: vars
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/$REPO-backend:latest
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ steps.vars.outputs.image_name }} ./backend
      - name: Push Docker image
        run: docker push ${{ steps.vars.outputs.image_name }}
