name: Docker Image CI

on:
  push:
    branches: [ "main", "refactor-to-backend-frontend" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refactor-to-backend-frontend
      - name: Build Docker image
        run: |
          cd backend
          docker build -t phpeasyreservation-backend:$(date +%s) .
