name: Docker Image CI

on:
  push:
    branches: [ "main", "refactor-to-backend-frontend" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refactor-to-backend-frontend
      - name: Set image name for backend
        id: vars-backend
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME_BACKEND=ghcr.io/$OWNER/$REPO/backend:latest
          echo "image_name=$IMAGE_NAME_BACKEND" >> $GITHUB_OUTPUT
      - name: Set image name for frontend
        id: vars-frontend
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME_FRONTEND=ghcr.io/$OWNER/$REPO/frontend:latest
          echo "image_name=$IMAGE_NAME_FRONTEND" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}
      - name: Build Docker image for backend
        run: docker build -t ${{ steps.vars-backend.outputs.image_name }} ./backend
      - name: Build Docker image for frontend
        run: docker build -t ${{ steps.vars-frontend.outputs.image_name }} ./frontend
      - name: Push Docker image for backend
        run: docker push ${{ steps.vars-backend.outputs.image_name }}
      - name: Push Docker image for frontend
        run: docker push ${{ steps.vars-frontend.outputs.image_name }}
